### ISSUE TITLE
ImportError: cannot import name 'SortedDict'

### ISSUE THREAD

**Issue by minhthe208** [aljosa/django-tinymce#114]
Hello Django-tinymce developers, I have just Upgraded Django 1.8.1 and I got this problem when I try to build my web application. Hope to see your reply soon, and sorry for my bad English

File "C:\Python34\lib\site-packages\tinymce\widgets.py", line 17, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name 'SortedDict'

**Comment by oelium** [comment]
you need to use collections.OrderedDict
so your import is like this in tinymce/widgets.py 

replace
from django.utils.datastructures import SortedDict
by
from collections import OrderedDict as SortedDict

in the same time it solve the Django warning : SortedDict deprecated an Removed in Django 1.9

read :  https://code.djangoproject.com/wiki/SortedDict
