### ISSUE TITLE
When order SortableStackedInline tinyMCE iframe content disappears

### ISSUE THREAD

**Issue by cubiczx** [aljosa/django-tinymce#116]
When order SortableStackedInline tinyMCE iframe content disappears, this not occurs with other editors as django-suit-redactor.

**Comment by SalahAdDin** [comment]
The same problem with django-ckeditor in django-suit? i think that could be a django-suit issue.

**Comment by cubiczx** [comment]
Y es is a django-suite error if change iframe forma div it works

**Comment by SalahAdDin** [comment]
Oh, then, please, say to @darklow about your solution for this bug :D
