### ISSUE TITLE
Django 1.8 Warning - url from future tag Removed in Django 1.9

### ISSUE THREAD

**Issue by oelium** [aljosa/django-tinymce#119]
RemovedInDjango19Warning: Loading the url tag from the future library is deprecated and will be removed in Django 1.9. Use the default url tag instead.
RemovedInDjango19Warning

In some template tinymce use the 'url' tag from the future.py module like this
{% load url from future %}
But in django 1.9 this tag will be removed.
You can find them in File: tinymce/templates/tinymce/tiny_mce_gzip.js line 1

so need to use directly {% url 'my_views' %}

![capture du 2015-07-23 14 10 55](https://cloud.githubusercontent.com/assets/13416461/8850007/ba44fcde-3144-11e5-859f-0c0f1a8dfb39.png)

**Comment by Natim** [comment]
Thanks a lot, see #120
