### ISSUE TITLE
Error on pip install django-tinymce

### ISSUE THREAD

**Issue by prattl** [aljosa/django-tinymce#121]
In a clean virtualenv with python2.7 and pip 7.1.0, the following produces an error: 
```
$ virtualenv env
$ source env/bin/activate
$ pip install Django==1.8.3
$ pip install django-tinymce
...
`IOError: [Errno 2] No such file or directory: '/tmp/pip-build-CZEtgL/django-tinymce/CHANGELOG.rst'`
```

**Comment by Natim** [comment]
I will fix it when I am back

**Comment by TippyTipster** [comment]
I have just encountered this error as well, same setup.

**Comment by Natim** [comment]
Fixed with https://github.com/aljosa/django-tinymce/commit/305c74ad7bcd1e70de4b73390bc4829088dffa5d
