### ISSUE TITLE
Post back to form issue

### ISSUE THREAD

**Issue by mdhanson1988** [aljosa/django-tinymce#123]
Recently installed Django TinyMCE via PIP.

Got the feature working via the form widget as advised in the docs (not the importing of js files in the template). I can do various text formatting via the widget but as soon as I submit the alterations the request.POST dictionary is passed the initial data and none of the alterations or the addition / removal of text.

Any ideas why this maybe happening?

**Comment by Natim** [comment]
Do you means that the initial data is not taking into account?

**Comment by vanadium23** [comment]
Close this issue due to related closed.
