### ISSUE TITLE
Setting TINYMCE_JQUERY_URL and configure jQuery url application wide

### ISSUE THREAD

**Issue by lives** [aljosa/django-tinymce#125]
Is there a way to configure the jquery to use in the django settings, something like TINYMCE_JQUERY_URL ?

This would avoid the explicit call to jquery in the templates
From :

```
<head>
<script src="/static/jquery/jquery-2.1.4.min.js"></script>
{{ form.media }}
</head
```

To :

```
<head>
{{ form.media }}
</head
```

**Comment by Natim** [comment]
AFAIK, it is not a bug but a feature because you don't want to include jQuery twice if you use if for something else. Either you are using TinyMCE in the admin, either you include jQuery to use django-tinymce

**Comment by Natim** [comment]
We should update the documentation about it here: http://django-tinymce.readthedocs.org/en/latest/usage.html#templates

**Comment by lives** [comment]
Ok, thank you for the answer
