### ISSUE TITLE
Plugin buttons in editor

### ISSUE THREAD

**Issue by laviritel** [aljosa/django-tinymce#126]
I'm using django-tinymce like a model field type, and i want to enable Paste plugin, but unfortunately there is no table button in edittor. So there is my config:

TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table",
    'theme': "advanced",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
	'width':800,
	'height':500,
}

**Comment by oelium** [comment]
Hi,
For me i set my TINYMCE_DEFAULT_CONFIG in settings file like this 
```python
TINYMCE_DEFAULT_CONFIG = {
    'theme': "advanced",
    'plugins': "plugin list with comma separate"
    'relative_urls': False,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'theme_advanced_resizing': True,
    'height': "600px",
    'width': "800px",
    'style_formats': [ list of dictonnary style ]
    'theme_advanced_buttons1': "list of button on the first row",
    'theme_advanced_buttons2':  "list of button on the second row",
    'theme_advanced_buttons3':  "list of button on the second row",
}
```
so it look like this

![capture du 2015-08-13 11 34 30](https://cloud.githubusercontent.com/assets/13416461/9246909/53c02e90-41af-11e5-98f1-2d2a806576a4.png)
