### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by lutoma** [aljosa/django-tinymce#127]
Just added django-tinymce to my Django installation. Everything works fine, the JavaScript static files load, the markup for the tinymce is added etc…

However, I'm getting the following JavaScript error in line 10 of django_tinymce.js:

    Uncaught TypeError: $ is not a function

Which seems to be caused by the changes in 6fa348f663af. If I replace the last line

```javascript
}( function (django) { return django && django.jQuery || jQuery }()));
```

with

```javascript
}( django && django.jQuery || jQuery ));
```

it works just fine. Didn't really check too much, but I think the main cause is the django argument of the nested function, which overrides the global django variable. Because there never actually is any argument passed in, the first check is always false and it ignores `django.jQuery` in the admin.

I guess an alternative solution would be passing the function the global django variable as an argument, but I'm not quite sure what the purpose of the extra nested function was anyways?

**Comment by Natim** [comment]
I've just released 2.0.4 with your fix. Thanks.
