### ISSUE TITLE
STATICFILES_DIRS support

### ISSUE THREAD

**Issue by Felix-neko** [aljosa/django-tinymce#130]
Good evening! Cannot you add support of STATICFILES_DIRS, when we use it instead of STATIC_ROOT in new versions of Django?

**Comment by aljosa** [comment]
@Felix-neko what are you trying to do?

**Comment by aljosa** [comment]
nevermind, just saw the PR

**Comment by Felix-neko** [comment]
So, can you pull it or somehow fix it in better way?

tinymce is really important for us.

**Comment by vanadium23** [comment]
PR was merged in master and go to v2.0.5. see #131
