### ISSUE TITLE
Widget not posting form data changes on non-admin page

### ISSUE THREAD

**Issue by hiltonc** [aljosa/django-tinymce#134]
I think this may be the same problem as #123, but I'm not sure so I'm opening a new issue.

When I use a TinyMCE widget in the admin it works perfectly. However, when I use the widget in a form in a non-admin page, any changes the user makes are not being posted when the form is submitted.

I checked the POST data in the browser's network developer tool, and I see the original contents of the field being posted, despite the fact that I changed the contents of the TinyMCE widget on page. Prior to submitting the form, I inspected the TinyMCE widget in the browser's inspector. My changes appear in it, but they are not reflected in the textarea form element. I'm not sure when my changes are supposed to be copied into the textarea, but that seems to not be happening.

Any ideas?

**Comment by hiltonc** [comment]
My problem was that I was using django-crispy-forms, which outputs the form media for each field. Having more than one TinyMCE field on the page, it caused the TinyMCE init code to run multiple times, which somehow broke things.

**Comment by dani0805** [comment]
We use tinymce (version 4) with crispy forms with multiple editors in more then one page. We switched to tinymce4 before introducing crispy forms so I do not know about v3.
