### ISSUE TITLE
Custom plugins

### ISSUE THREAD

**Issue by 9dogs** [aljosa/django-tinymce#136]
Hi, is there any way to define custom plugins to use with django-tinymce?
I'm trying to create simple typograph plugin based on [this article](http://habrahabr.ru/post/266337/#typograf) [rus]. Anyway, the plugin js should look like this:
```javascript
tinymce.PluginManager.add('typograf', function (editor, url) {
    'use strict';

    var scriptLoader = new tinymce.dom.ScriptLoader(),
        tp,
        typo = function () {
            if (tp) {
                editor.setContent(tp.execute(editor.getContent()));
                editor.undoManager.add();
            }
        };

    scriptLoader.add(url + '/typograf.min.js');

    scriptLoader.loadQueue(function () {
        tp = new Typograf({
            lang: 'ru',
            mode: 'name'
        });
    });

    editor.addButton('typograf', {
        text: 'Typograph',
        icon: 'blockquote',
        onclick: typo
    });

    editor.addMenuItem('typograf', {
        context: 'format',
        text: 'Typograph',
        icon: 'blockquote',
        onclick: typo
    });
});

```

The problem is Django Media assets [has no dependency mechanism](https://code.djangoproject.com/ticket/12265) AFAIK, so just adding `js = ['custom-plugin.js', ]` in Media class in my ModelAdmin results in `Uncaught ReferenceError: tinymce is not defined` (as expected, because custom-plugin.js loads before tinymce.min.js). 

Is there any right way to add custom plugin in django-tinymce?

**Comment by dani0805** [comment]
If you want to add buttons to your editor you can use tinymce setup event, if your are using tinymce4 you would need to add an entry in the profile in your settings with the javascript function to be called. Like this (red line):

TINYMCE_PROFILE = {
    'theme': 'modern',
    'plugins': 'noneditable advlist autolink link lists charmap hr searchreplace wordcount visualblocks visualchars code insertdatetime save table contextmenu directionality paste textcolor',
    'toolbar': 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | forecolor backcolor | standard_content_button upload_button template_button | preview_button',
    'noneditable_leave_contenteditable': 'true',
    'setup': 'addCustomButtons',
    'content_css': os.path.join(STATIC_URL, "mis/css/tinytiny.css"),
    'relative_urls': False,
    'remove_script_host': True,
    'document_base_url': MEDIS_APP_HOST,
    'removed_menuitems': 'newdocument'
}

**Comment by 9dogs** [comment]
Thank you for reply!
Indeed, I've missed tinymce [setup option](http://www.tinymce.com/wiki.php/Configuration:setup), which provide a way to call any javascript after all tinymce js is loaded. Another way is to create `tinymce/plugins/your_plugin` somewhere in your `static` folders, place all your js file there and then include `your_plugin` in `TINYMCE_PROFILE['plugins']` list. Still not sure which way is better but anyhow the problem is solved. Thanks again.

**Comment by Natim** [comment]
>  Still not sure which way is better but anyhow the problem is solved.

If you need to use tinymce_compressed then adding it in the static is better.
Do you mind contributing a paragraph in the documentation to explain how you solved it?

**Comment by 9dogs** [comment]
>If you need to use tinymce_compressed then adding it in the static is better.

Yes, it's more straightforward too.
>Do you mind contributing a paragraph in the documentation to explain how you solved it?

Sure. Should I fork and then send pull request?

**Comment by Natim** [comment]
> Should I fork and then send pull request?

Yes please, if you feel like it.
