### ISSUE TITLE
Compressor does not work at all in Python 3

### ISSUE THREAD

**Issue by jribbens** [aljosa/django-tinymce#144]
`compressor.py` adds a bunch of string literals to the `content` list and then calls `.decode` on each of them. Obviously this cannot work on Python 3 since you can't "decode" a Unicode string.

**Comment by vanadium23** [comment]
I have rewrite compressor with py3k support. Hope it'll work.

**Comment by vanadium23** [comment]
We've released 2.3.0 - try to check this bug.

**Comment by jribbens** [comment]
Looks like it works for me now (Python 3.4.3, Django 1.9.4, django-tinymce 2.3.0).

**Comment by Natim** [comment]
Thank you @jribbens for your feedback :)
