### ISSUE TITLE
django-tinymce future and tests

### ISSUE THREAD

**Issue by Natim** [aljosa/django-tinymce#149]
**Fact: A number of people relies on django-tinymce for their application.**

In order to guarantee the quality and the maintenance of this project we should write tests so that we can guarantee which version of Python and Django django-tinymce is working with.

Today there are manual tests that can let us see if django-tinymce is working in the admin and in a form but we need to automate this tests and make them run on travis-ci.

The good news is that Django comes with [Selenium integration](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#liveservertestcase) so it should not be that hard.

Feel free to add things that you think should be tested here so that we can plan an effective roadmap of what should be tested.

**Unit tests**
- [x] [HTMLField](https://github.com/aljosa/django-tinymce/blob/master/tinymce/models.py#L13-L26) default widget should be [tinymce.widgets.AdminTinyMCE](https://github.com/aljosa/django-tinymce/blob/master/tinymce/widgets.py#L119-L120)
- [x] [get_language_config ](https://github.com/aljosa/django-tinymce/blob/master/tinymce/widgets.py#L123-L156)
- [x] [TinyMCE textarea widget](https://github.com/aljosa/django-tinymce/blob/master/tinymce/widgets.py#L33-L116)
- [ ] [URLs](https://github.com/aljosa/django-tinymce/blob/master/tinymce/urls.py) are well defined.
- [x] [spell_check view](https://github.com/aljosa/django-tinymce/blob/master/tinymce/views.py#L38-L73)
- [x] [flatpage_link_list view](https://github.com/aljosa/django-tinymce/blob/master/tinymce/views.py#L95-L102)
- [x] [compressor view](https://github.com/aljosa/django-tinymce/blob/master/tinymce/views.py#L105-L109)
- [x] [filebrowser view](https://github.com/aljosa/django-tinymce/blob/master/tinymce/views.py#L132-L139)
- [ ] [staticfiles and default settings](https://github.com/aljosa/django-tinymce/blob/master/tinymce/settings.py#L5-L22)
- [x] [compressor tinymce plugins file gathering](https://github.com/aljosa/django-tinymce/blob/master/tinymce/compressor.py)
- [x] [tinymce_preview templatetag](https://github.com/aljosa/django-tinymce/blob/master/tinymce/templatetags/tinymce_tags.py#L11-L13)

**Functional test**
- [ ] Tinymce loading in the admin (with and without compressor and with plugins)
- [ ] Tinymce loading in a form (with and without compressor and with plugins)

**We need you to help**

So if you are using TinyMCE and plan on keep using it file a Pull Request and add a test I will be there to help in the process.

**Comment by Natim** [comment]
Once we've done that we could consider applying for [Jazzband Collaborative](https://jazzband.co/)

**Comment by jezdez** [comment]
@Natim +1

**Comment by vanadium23** [comment]
@jezdez we somehow covered our lib with test. What else should be done to apply to jazzband?
