### ISSUE TITLE
it's do not work,help me

### ISSUE THREAD

**Issue by imbyron** [aljosa/django-tinymce#150]
Please help me, i have not use `class MyModel(models.Model):`, i use `admin.ModelAdmin`
my code is:
```
from django.contrib import admin
from models import *
from tinymce.models import HTMLField
class ArticleAdmin(admin.ModelAdmin):
    list_display = ('title', 'desc', 'user', 'category')
    list_display_links = ('title', 'desc', 'user', 'category')
    # fields = ('title', 'desc', 'content',)
    content = HTMLField()
```
how can i do?

**Comment by vaibhav-jain** [comment]
@imbyron Try [this](http://stackoverflow.com/questions/4176613/django-admin-using-a-custom-widget-for-only-one-model-field) and for more info read [here ](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides)

**Comment by vanadium23** [comment]
@imbyron does comment above solve problem?
