### ISSUE TITLE
Switch to tinymce 4.x

### ISSUE THREAD

**Issue by vanadium23** [aljosa/django-tinymce#160]
We are starting a big road towards implementing tinymce 4.x in main repository.
More detailed proposal will be done by @aljosa.

**Comment by And-Sm** [comment]
Any updates?

**Comment by PazzaVlad** [comment]
Yeah, it would be nice to see new version)

**Comment by applecat** [comment]
Any news about switch to 4.x?

**Comment by vanadium23** [comment]
Currently I passed refactored lib to collaborators and gather some feedbacks. This version will go towards minimal principal, but with breaking changes.

**Comment by kudlatyamroth** [comment]
any news on that?

**Comment by dsummersl** [comment]
Any news on support for tinymce v4?

**Comment by Flimm** [comment]
Is there any way we can help to get this working with tinymce 4.x?

**Comment by emorozov** [comment]
I have switched to django-tinymce4-lite. It's a drop-in replacement, almost no changes to the application source code necessary. Posting this comment because maybe some poor soul is waiting for several years when django-tinymce will finally support the latest tinymce version...

**Comment by iMerica** [comment]
Thank you so much @emorozov 🙏
