### ISSUE TITLE
How can I set up TinyMCE for Admin

### ISSUE THREAD

**Issue by boopr** [aljosa/django-tinymce#162]
Hello,
The documentation isn't really helpful for this... So I'm trying to install TinyMCE for the Django Admin panel but I can't figure out how to do this...

Hope someone will be able to help me !
Thanks

**Comment by vanadium23** [comment]
You can either use an Widget (http://django-tinymce.readthedocs.org/en/latest/usage.html#python-code) or setup an HTMLField in your model from quick README.md

**Comment by GuidoBrasil** [comment]
Hi, 

I have been able to setup the TinyMCE for Admin. I have though a minor issue which I would like to clear up. I have been using the HTMLField setup and indeed it appears nicely. However the label for the field is "hidden" behind the TinyMCE editor. How could I solve that? 

![screen shot 2016-03-14 at 11 26 17](https://cloud.githubusercontent.com/assets/2990873/13747588/bc55a1b2-e9d7-11e5-81af-849bccde0090.png)

**Comment by vanadium23** [comment]
Which version of django do you have?

**Comment by GuidoBrasil** [comment]
I am using 1.8.4. For now I have solved the issue playing around with the skin.min.css from the tinymce. 

.mce-tinymce {
    display: block !important;
    width: 94%;
    float: right;
}

that does the trick.. but I  guess there is a more solid solution?

**Comment by vanadium23** [comment]
Need to investigate more for this behaviour, so can you open new issue for that with info provided above.
