### ISSUE TITLE
Setting up TinyMce for admin the lable gets hidden behind the tinymce field

### ISSUE THREAD

**Issue by GuidoBrasil** [aljosa/django-tinymce#164]
Hi,

I have been able to setup the TinyMCE for Admin. I have though a minor issue which I would like to clear up. I have been using the HTMLField setup and indeed it appears nicely. However the label for the field is "hidden" behind the TinyMCE editor. How could I solve that?

![screen shot 2016-03-14 at 11 26 17](https://cloud.githubusercontent.com/assets/2990873/13749157/ef6b2fde-e9de-11e5-8dcc-0a9a1b847c44.png)

For now I have solved the issue editing the skin.min.css

.mce-tinymce {
    display: block !important;
    width: 94%;
    float: right;
}

I hope though there could be a more solid solution? 

Thanks in advance!

**Comment by urtzai** [comment]
+1

**Comment by fallen** [comment]
+1
