### ISSUE TITLE
 ValueError: zero length field name in format - python 2.6

### ISSUE THREAD

**Issue by rizework** [aljosa/django-tinymce#165]
>  File "/usr/local/lib/python2.6/dist-packages/django/forms/forms.py", line 411, in __unicode__
>     return self.as_widget()
> 
>   File "/usr/local/lib/python2.6/dist-packages/django/forms/forms.py", line 458, in as_widget
>     return widget.render(name, self.value(), attrs=attrs)
> 
>   File "/usr/local/lib/python2.6/dist-packages/tinymce/widgets.py", line 92, in render
>     mce_config = self.get_mce_config(final_attrs)
> 
>   File "/usr/local/lib/python2.6/dist-packages/tinymce/widgets.py", line 63, in get_mce_config
>     mce_config.update(get_language_config(self.content_language))
> 
>   File "/usr/local/lib/python2.6/dist-packages/tinymce/widgets.py", line 144, in get_language_config
>     sp_langs.append('{!s}{!s}={!s}'.format(default, ' / '.join(names), lang))
> 
> ValueError: zero length field name in format

TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,paste,fullscreen,media,advlink",
    'theme': "advanced",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'paste_text_sticky': True,
    'paste_text_sticky_default' : True,
    'theme_advanced_buttons4' : "cut,copy,paste,pastetext,pasteword,|,fullscreen",
    'file_browser_callback': 'mce_filebrowser',
    'file_picker_types': 'file,image',
}
django-tinymce-2.3.0

**Comment by aljosa** [comment]
from @rizework email:
"The problem is new python style .format which is not supported in python 2.6 .. {!s}"

if anybody else has this issue:
"Python 2.6 is no longer supported but I think django-tinymce 2.2.0 should work.
If not, try a previous release."
