### ISSUE TITLE
smart_text import in compressor.py breaks support for Django 1.4.1 and prior

### ISSUE THREAD

**Issue by mattarchie** [aljosa/django-tinymce#167]
#158 adds `from django.utils.encoding import smart_text` to compressor.py

I was able to upgrade my project to use Django 1.4.2, which seems to be the first version to enable smart_text to be used in place of smart_unicode (I believe in all 1.4.2+ versions it is an alias, but eventually smart_text replaces smart_unicode at some point). Anyway, I just wanted to let you know so that you can update your documentation to say that Django 1.4.2+ is required now. That, or I believe it may be possible to do a try catch on the ImportError and import smart_unicode as smart_text if smart_text isn't available.

**Comment by vanadium23** [comment]
Thanks. We've updated documentation and say that this plugin support from 1.6+
