### ISSUE TITLE
Static files, storage

### ISSUE THREAD

**Issue by dilrajsachdev** [aljosa/django-tinymce#172]
Hi,

I am using S3 storage for static files with custom URLs but this is not supporting for now

On my local I modified the settings.py like this to get proper urls

`from django.contrib.staticfiles.storage import staticfiles_storage`

`JS_URL = staticfiles_storage.url('tiny_mce/tiny_mce.js')`
`JS_ROOT = staticfiles_storage.url('tiny_mce')`

And I made similar changes in widget.py also

If you would like then I can make pull request

Thanks

**Comment by Natim** [comment]
I really loved to see this storage story fixed in master. If you want to work on it you are welcome.
