### ISSUE TITLE
How do I add youtube plugin ?

### ISSUE THREAD

**Issue by Anton-Shutik** [aljosa/django-tinymce#178]
I've tried this:

``` python
def formfield_for_dbfield(self, db_field, **kwargs):
        if db_field.name == 'text':
            kwargs['widget'] = AdminTinyMCE(
                attrs={'cols': 80, 'rows': 30},
                mce_attrs={
                    'plugins': 'youtube',
                    'theme': 'advanced'
                })
        return super(ModelAdmin, self).formfield_for_dbfield(db_field, **kwargs)
```

I see this:
![image](https://cloud.githubusercontent.com/assets/1625053/15590137/b3296d48-239e-11e6-98c9-8424d0fc77ce.png)

any ideas whats wrong ?
using django-tinymce==2.3.0

**Comment by Lewiscowles1986** [comment]
Is the youtube plugin installed in the tinymce plugins folder, and is the version of tinymce compatible with the youtube tinymce plugin?

These are the first two things I'd check. It seems to work with my custom plugin and the bbcode plugin
