### ISSUE TITLE
Using a named view no longer works

### ISSUE THREAD

**Issue by Apophenian** [aljosa/django-tinymce#180]
It seems the views for this were removed here: https://github.com/aljosa/django-tinymce/commit/1535f5c33544c4ac49d397ec14e2ec88e177587d#diff-99f82678a1ffa0a31e0576ec938419c9

But it's still documented here: http://django-tinymce.readthedocs.io/en/latest/usage.html#using-the-view

**Comment by danigosa** [comment]
They are used in 3rd party libs like zinnia-wysiwyg-tinymce, this change broke everything, a workaround on this?

**Comment by Apophenian** [comment]
I copied the view and urls entries that were removed into my own code, but it's a bit nasty!
