### ISSUE TITLE
Required fields and browser validation

### ISSUE THREAD

**Issue by claudep** [aljosa/django-tinymce#187]
Apparently, when a textarea having the `required` attribute is powered by TinyMCE, browser validation (Firefox tested) is preventing form submission, as the textarea itself is considered empty by the browser.
This can be workarounded by using `TinyMCE(attrs={'required': False})` as widget definition in the Django form. I've also seen some JS snippets trying to fix this.

Is this something django-tinymce should force doing?

**Comment by Elwro** [comment]
I just wanted to add that I think I'm having a similar issue, described here:[http://stackoverflow.com/questions/40662092/form-stopped-saving-to-database-after-textfield-was-changed-to-htmlfield](url) 

And unfortunately, using the `'required': False` attribute did not help in my case...

**Comment by claudep** [comment]
I also eventually had to subclass the widget:
```
class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False
```

**Comment by Elwro** [comment]
Thank you very much, this does the trick.

**Comment by tylerecouture** [comment]
+1
