### ISSUE TITLE
Double jquery when using 2.4.0

### ISSUE THREAD

**Issue by hakjoon** [aljosa/django-tinymce#190]
After upgrading to 2.4.0 the Tinymce widget is adding its own version of jquery.  We already include jQuery in our templates so this is causing a double load.  Is there a away to configure this?  This was not the case with 2.3.0.

This seems to have been [introduced as part of the grappelli fix](https://github.com/aljosa/django-tinymce/commit/8aca4af6d6be06e68c2fce2779679875b11c302e#diff-4db5bdcb4b5468a0bad84aa0d2a7aa64R114)

**Comment by dsummersl** [comment]
ditto +1
