### ISSUE TITLE
I cant save form 

### ISSUE THREAD

**Issue by ghost** [aljosa/django-tinymce#193]
I cant save form with a textarea that uses django-tinymce. 

The button info is: `<input type="submit" class="super normal button" value="{% trans "Submit" %}" name="submit"/>`

Here is someone with a  [similar problem](https://stackoverflow.com/questions/38997237/django-tinymce-submit-button-not-working). Thank you.

Django Version:1.10
Django-Tinymce Version: 2.3.0

**Comment by claudep** [comment]
If the affected model field is a required one, this might be a duplicate of #187.
