### ISSUE TITLE
Update latest minor version of TinyMCE 3.5 to version 1.5

### ISSUE THREAD

**Issue by tomijarvi** [aljosa/django-tinymce#208]
Hi,

The django-tinymce version 1.5.3 contains TinyMCE 3.5.8 which has got several fixes after that. Could you update the TinyMCE version 3.5.12 to django-tinymce version 1.5 or do I create a fork?

Thanks

**Comment by Natim** [comment]
Can you submit a PR for it?

**Comment by tomijarvi** [comment]
Sure

**Comment by Natim** [comment]
Thanks

**Comment by tomijarvi** [comment]
@Natim: Could you create branch from the 1.5 so I will send PR for you.

**Comment by Natim** [comment]
Why do you want it from the 1.5 branch?

**Comment by tomijarvi** [comment]
We have old django projects which are older than django 1.6 and for those projects, django upgrade is not coming for a while.

**Comment by tomijarvi** [comment]
Released: https://github.com/aljosa/django-tinymce/releases/tag/1.5.4

@Natim: Thank you very much!

**Comment by Flimm** [comment]
I was going to suggest closing this PR since the fix is merged and published. However, I'm confused by this latest tag in the Git repo: https://github.com/aljosa/django-tinymce/releases/tag/1.5.4

Aren't the tags supposed to be version numbers of `django-tinymce`? Why is the tag 2.6.0 followed by the tag 1.5.4?

**Comment by Natim** [comment]
It is probably because we did a patched release on this branch and pypi uses the last push as the most up-to-date version. I am fixing it right away, thanks for noticing

**Comment by Natim** [comment]
Actually it was already correct when I checked: https://pypi.python.org/pypi/django-tinymce is 2.6.0

**Comment by Natim** [comment]
Oh sorry you were talking about the release page on Github. It is because the patched release simply happened after the release of 2.6.0

**Comment by Flimm** [comment]
Ah, I see, you're releasing bugfixes for old versions of `django-tinymce`. That makes sense.

**Comment by Natim** [comment]
It happened once yes.
