### ISSUE TITLE
TinyMCE not initialized after an inline is added

### ISSUE THREAD

**Issue by user-45-20** [aljosa/django-tinymce#210]
I'm on Django 1.10; one of the recent versions must have changed the DOM slightly (I'm not intimately familiar with the Django admin templates; perhaps the DOM is different from what the author of django-tinymce it would look like because of my model definitions?), and the "Add another <modelname>" button now uses the following hierarchy:

```
<tbody>
  <item 1>
  <item 2>
  ...
  <tr class="add-row">
    <td>
      <a href="#">Add another <model name></a>
    </td>
  </tr>
  ...
</tbody>
```

As a result, the JS code in init_tinymce.js fails:
`if(!ev.target.parentNode || ev.target.parentNode.className.indexOf("add-row") === -1)`
this condition is never satisfied, because `ev.target.parentNode.className` is empty (since the parent is the `td` node). A simple fix is to do this instead:

```
if (!ev.target.parentNode || 
    !ev.target.parentNode.parentNode ||
    ev.target.parentNode.parentNode.className.indexOf("add-row") === -1) {
  return;
}
var $addRow = $(ev.target.parentNode.parentNode);
```

**Comment by istals** [comment]
The issue still persists on this repo, as I can see it is only fixed for lite version

**Comment by vvalentinvolkov** [comment]
I have the same issue. Django = 4.1, django-tinumce=3.6.1
