### ISSUE TITLE
Just upgraded to Django 1.11 and TinyMCE crashed

### ISSUE THREAD

**Issue by huydbui** [aljosa/django-tinymce#212]
```
File "/usr/local/lib/python3.6/site-packages/tinymce/widgets.py", line 17, in <module>
    from django.forms.widgets import flatatt
ImportError: cannot import name 'flatatt'
```

Upon checking Django documentation for Django 1.11, "flatatt" is gone.
Link https://docs.djangoproject.com/en/1.11/_modules/django/forms/widgets/
Changing the Documentation Version at the bottom right corner of the page from 1.11 to 1.10 shows the line: **from django.forms.widgets import flatatt** (this has been removed since 1.11)

Please advice.

Best,
Huy.

**Comment by Natim** [comment]
I don't see anything about that there: https://docs.djangoproject.com/en/1.11/releases/1.11/

**Comment by claudep** [comment]
This was fixed in 198b83780f9, did you install the latest version?

**Comment by Natim** [comment]
I guess you can use this: https://github.com/django/django/blob/1.10.7/django/forms/utils.py#L26-L49 by backporting it directly to your project.

**Comment by huydbui** [comment]
Impressive! Less than 2 minutes, my issue is resolved. I love the community. I apologize for not checking the tinymce version/logs before creating new issue.

I will do better next time.

Thank you @claudep @Natim
