### ISSUE TITLE
customization of tinymce toolbar in "advanced" theme

### ISSUE THREAD

**Issue by fugokidi** [aljosa/django-tinymce#213]
I want to reduce the number of items in tinymce used in a form widget. I put tinymce config in the django settings as follows.

```
TINYMCE_DEFAULT_CONFIG = {
    'theme': "advanced",
    'toolbar': "undo redo | styleselect | bold italic | link image",
    'width': 300,
}
```
The width options actually changed the the width of the widget, but the toolbar doesn't get changed.
How can I override toolbar config from django-tinymce?

**Comment by Natim** [comment]
I did find max_width and min_width but not width here: https://www.tinymce.com/docs/configure/editor-appearance/#max_width
