### ISSUE TITLE
INCLUDE_JQUERY = False not being respected?

### ISSUE THREAD

**Issue by voodoo-burger** [aljosa/django-tinymce#216]
I've added `TINYMCE_INCLUDE_JQUERY = False` in my settings.py, but the jQuery file is still being loaded with `{{ form.media }}`. Is this setting only designed to work when using the widget? I am using the HTMLField model field. Django 1.11.1 on Python 3.6 .

**Comment by claudep** [comment]
Did you install django-tinymce from Git master?

**Comment by voodoo-burger** [comment]
No, I installed with pip. I have version 2.6.0 .

**Comment by claudep** [comment]
That explains it, the `INCLUDE_JQUERY` functionality is not yet released.

**Comment by Natim** [comment]
It has been released in the last django-tinymce 2.7 release.
