### ISSUE TITLE
Install Plugin?

### ISSUE THREAD

**Issue by alzearafat** [aljosa/django-tinymce#217]
Hi there!

How I can install custom plugin? I want to add this plugin : https://www.tinymce.com/docs/plugins/codesample/

It seems I cannot find anywhere on the docs, or maybe I just missed it?

Any help would be greatly appreciated!
Thanks.

**Comment by Natim** [comment]
I did that in the past, I think you need to provide your own tinymce static repository, you should be able to just add the plugin and it will merge. We should probably document that.

**Comment by alzearafat** [comment]
Hi @Natim 

Thanks for the reply. But sorry I still don't get it :/
Can you please elaborate? What tinymce static repository?

Thank you!

**Comment by Natim** [comment]
In your django app you can use a [static directory](https://docs.djangoproject.com/en/2.0/howto/static-files/) to expose the tinymce JS code.

**Comment by Natim** [comment]
Here is the code that ships with django-tinymce: https://github.com/aljosa/django-tinymce/tree/master/tinymce/static/tiny_mce

If you create a `static/tiny_mce` repository in your app that expose the plugin code you should be fine.

**Comment by alzearafat** [comment]
Hi @Natim 

Ahh... I see... Much clearer now!
Thank you! 😃
