### ISSUE TITLE
Trouble Getting the tinymce css to show in the Django Admin

### ISSUE THREAD

**Issue by gatensj** [aljosa/django-tinymce#218]
Hey there.  As the title suggests, I am having trouble seeing the tinymce's associated CSS files.  

In order to help diagnose this problem, let me give you some background on my project.  To start I pip installed the django-tinymce into my project.  From there, I added 'tinymce'  to my installed_apps in my settings.py and updated the urls.py accordingly.  Also in my settings.py I added the code listed beneath this message.  On my Post model I added a field, content = HTMLField().  So when I go to the admin in the browser, and navigate to the model in question - all the fields render.  Except the tinymce editor does not load the corresponding CSS files.  

http://debug.example.org/tiny_mce/themes/advanced/skins/default/ui.css 
http://debug.example.org/tiny_mce/themes/advanced/skins/default/content.css 
http://debug.example.org/tiny_mce/plugins/spellchecker/css/content.css

Any and all help would greatly be appreciated.  Thanks for reading.  Take care and have a good day.

Sincerely,

JG

xxxxxxx
STATIC_JS_DIR = os.path.join(STATIC_ROOT, "js")

TINYMCE_JS_ROOT = "../static/django-tinymce/tinymce/static/tiny_mce"
TINYMCE_JS_URL = os.path.join(TINYMCE_JS_ROOT, "tiny_mce.js")

TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,spellchecker,paste,searchreplace",
    'theme': "advanced",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
}
TINYMCE_SPELLCHECKER = True
TINYMCE_COMPRESSOR = True
xxxxxxx

**Comment by gatensj** [comment]
Also in addition to the above statement, I moved the "django-tinymce" folder inside the static directory.

**Comment by shershen08** [comment]
What helped in my case is to add underscore, as it is in the folder
`TINYMCE_JS_URL = STATIC_URL + 'tiny_mce/tiny_mce_src.js'`
mind the **tiny_mce/** not **tinymce/**
