### ISSUE TITLE
Change Theme/Skin

### ISSUE THREAD

**Issue by zaktimson** [aljosa/django-tinymce#221]
Hey there! I have managed to get this tinymce working but I want to change the theme to match the rest of the site.

Here is what it currently looks like:
![image](https://user-images.githubusercontent.com/5761827/30034060-e5bc84d8-916c-11e7-9c8b-b4e4c94615c3.png)

I would like to make it look like the one on their site:
![image](https://user-images.githubusercontent.com/5761827/30034073-f82681dc-916c-11e7-8df9-3c78594acfcc.png)

I have looked everywhere and tried copying some files into `/static/tinymce/theme/lightgray` with no success.

Here is my current settings:
```
TINYMCE_DEFAULT_CONFIG = {
    'width': '100%',
    'theme': 'advanced',
    'skin': 'default'
}
```

Any help would be greatly appreciated.

**Comment by leonardopessoa** [comment]
This is probably because django-tinymce hasn't updated to the original TinyMCE v4.0
Up vote here to do that update. Their new theme looks awesome

**Comment by Natim** [comment]
You can use TinyMCE 4 with this module: https://github.com/dani0805/django-tinymce4
