### ISSUE TITLE
How to convert the content of HTML Field to AMP(Accelerated Mobile Pages)? 

### ISSUE THREAD

**Issue by shubh261994** [aljosa/django-tinymce#223]
I want to convert the tags inside the HTML Field to amp tags. How can I do it?

**Comment by atodorov** [comment]
As far as I understand AMP is HTML with some custom rules on top of it. OTOH django-tinymce provides just the integration between the TinyMCE editor and Django. There is a template tag provided by this library and a widget which is rendered with a textarea tag. 

@shubh261994 can you clarify what exactly do you want to convert to AMP? Give example if possible so I can understand you better.
