### ISSUE TITLE
i cant Quickstart

### ISSUE THREAD

**Issue by am120sec** [aljosa/django-tinymce#235]
When migrating using HTMLField in model.py, the following error is displayed.
`AttributeError: module 'django.db.models' has no attribute 'HTMLField`
In "Quickstart", you can use HTMLField in four steps, but you can not.

I am using Django 2.0.3.

What is the cause?

**Comment by BronzeCrab** [comment]
I think you ve made something like:
```
from django.db import models

class Test(models.Model):
    content = models.HTMLField()
```
but you need to :
```
from tinymce.models import HTMLField
class Test(models.Model):
    content = HTMLField()
```
