### ISSUE TITLE
Upgrade TinyMCE to 4.0?

### ISSUE THREAD

**Issue by YiiKuoChong** [aljosa/django-tinymce#238]
I noticed that the project uses an old TinyMCE version with some plugins and themes not available out of the box. 

Is it okay to upgrade it to TinyMCE 4.0?

**Comment by adinvadim** [comment]
@aljosa What do you think?

**Comment by aljosa** [comment]
@YiiKuoChong @adinvadim there are a couple of forks and new apps that work with tinymce v4.
please use them instead of this app if you need newer version
