### ISSUE TITLE
Is there a typo in release version?

### ISSUE THREAD

**Issue by subodh-malgonde** [aljosa/django-tinymce#249]
The release on 21st Jan 2019 has version `2.6.1`. The release before this one, on 15th Jan 2019, had version `2.8.0`. 

Did you mean to release `2.8.1` or am I missing something?

![Screen Shot 2019-06-12 at 5 52 07 PM](https://user-images.githubusercontent.com/5463437/59350917-d9034300-8d3a-11e9-9e38-a9ddc6112f38.png)

**Comment by Natim** [comment]
We did release a bugfix for multiple releases, however the last one is 2.8.0
