### ISSUE TITLE
Error on Django 2.2

### ISSUE THREAD

**Issue by saadat99** [aljosa/django-tinymce#251]
When I add TinyMCE to my INSTALLED_APPS I get this error 
Django 2.2.4
https://stackoverflow.com/q/57315449/7400518
```
SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E404) 'django.contrib.messages.context_processors.messages' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin application.
```

**Comment by Natim** [comment]
Make sure to add the `django.contrib.messages.context_processors.messages` in your settings.py 

https://docs.djangoproject.com/en/2.2/topics/templates/#django.template.backends.django.DjangoTemplates

```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]
```

**Comment by saadat99** [comment]
`django.contrib.messages.context_processors.messages` is present in settings.py. I think issue is from the package

**Comment by kabilovtoha** [comment]
"django.contrib.messages.context_processors.messages",
must be before :
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
