### ISSUE TITLE
Widget in Admin breaks Select2 JS

### ISSUE THREAD

**Issue by MalachiDraven** [aljosa/django-tinymce#255]
When adding the TinyMCE widget to the Admin, it's breaking the fields that are set under the ModelAdmin's autocomplete_fields setting. The console is giving the following error message:

`TypeError: $element.select2 is not a function` coming from autocomplete.js

I've tested with different ways of adding TinyMCE to the Admin - formfield_overrides for widget, custom ModelForm, and the HTMLField. They all break the autocomplete_fields. It seems rendering TinyMCE on the page is somehow preventing Django's built-in Select2 JS from loading.

EDIT: Actually, it seems that TinyMCE is breaking **all** Select2 JS, even if I'm using the django-select2 package for it. My other Select2Widget and Select2MultipleWidget fields all break as soon as I enable the TinyMCE widget. This gives the following error:

`TypeError: $ is undefined` from django_select2.js

**Comment by silviomoreto** [comment]
Why this issue was closed? I am having the same issue

**Comment by claudep** [comment]
Probably because this is a duplicate of #282?
