### ISSUE TITLE
3.0.1 missing list functionality (bulleted & number lists missing)

### ISSUE THREAD

**Issue by ZackPlauche** [aljosa/django-tinymce#262]
I was using django-tinymce 2.8.0 and accidentally added 3.0.1 to my new requirements.txt file.

The interface looks cleaner, however, I lost the ability to add list items to it which is definitely a problem.

I might be missing something that I haven't seen in the docs for it. Please add this feature back to default.
![2020-04-22_15-51-52](https://user-images.githubusercontent.com/43456955/79985683-a6c28600-84b3-11ea-8780-59c1b2770f81.jpg)
![2020-04-22_16-05-04](https://user-images.githubusercontent.com/43456955/79985686-a88c4980-84b3-11ea-9679-e79311779440.jpg)

**Comment by Natim** [comment]
@ZackPlauche that's definitely a problem. Would you have time investigate why and propose a fix?

**Comment by Natim** [comment]
I guess it is related to the list plugin that is missing somehow, https://www.tiny.cloud/docs/plugins/lists/

**Comment by ZackPlauche** [comment]
Ah, I didn't see in the documentation how to really make these changes.

I think adding it to default would be good as it's such a common function among blogs and what not.

That bulleted and number lists.

**Comment by Natim** [comment]
![image](https://user-images.githubusercontent.com/229453/79987833-2e0cfb00-84ae-11ea-969b-57d9ea30a14b.png)

**Comment by ZackPlauche** [comment]
This looks amazing!

**Comment by Natim** [comment]
a83c0e7

**Comment by Natim** [comment]
@ZackPlauche you might want to have a look at this config too:

https://github.com/aljosa/django-tinymce/issues/261#issuecomment-614853993
