### ISSUE TITLE
Update TINYMCE_DEFAULT_CONFIG like a dictionary

### ISSUE THREAD

**Issue by shawnngtq** [aljosa/django-tinymce#264]
I wonder if there is a way I can update TINYMCE_DEFAULT_CONFIG without copying the default into my project's `settings.py`.

I would prefer not to copy the entire TINYMCE_DEFAULT_CONFIG so that when there is any update to this package, the TINYMCE_DEFAULT_CONFIG will always be the latest default configuration.

**Specific custom change I want**:  enable menubar. 

I tried the following
```
# method 1
TINYMCE_DEFAULT_CONFIG["menubar"] = True

# method 2
TINYMCE_DEFAULT_CONFIG.update({"menubar": True})
```

The above attempt don't work as `NameError: name 'TINYMCE_DEFAULT_CONFIG' is not defined`.

I wonder if I can import the default TINYMCE_DEFAULT_CONFIG from some path in order for the above code to work.

Thanks!

**Comment by Natim** [comment]
You can try adding `from tinymce.settings import TINYMCE_DEFAULT_CONFIG` before updating it.
You might endup with a circular import though.
