### ISSUE TITLE
HTMLField is not appeared in Django Admin Site

### ISSUE THREAD

**Issue by zhicheng22** [aljosa/django-tinymce#290]
![2020-08-26_06-36](https://user-images.githubusercontent.com/61251512/91235095-5ad86400-e767-11ea-8f1b-e81e4ded67d4.png)
![2020-08-26_06-37](https://user-images.githubusercontent.com/61251512/91235098-5ca22780-e767-11ea-8e2a-532fdd10a8db.png)
![2020-08-26_06-37_1](https://user-images.githubusercontent.com/61251512/91235099-5d3abe00-e767-11ea-92e5-1eea6cab1cae.png)
![2020-08-26_06-39](https://user-images.githubusercontent.com/61251512/91235101-5d3abe00-e767-11ea-8efc-49461297b51a.png)
![2020-08-26_06-40](https://user-images.githubusercontent.com/61251512/91235102-5dd35480-e767-11ea-8f7f-00f97d8c4d1b.png)

Here are my codes.

My code was working well with Django==2.0.8, django-tinymce==2.7.0.
I updated my codes with Django=2.2.15, django-tinymce==3.0.2

Please help me.
Thanks.

**Comment by Natim** [comment]
Your configuration is for an old version of TinyMCE. Don't upgrade to the last version if you don't want to upgrade your configuration to meet TinyMCE 5 requirements.

**Comment by zhicheng22** [comment]
How should I update my Tinymce configuration for Django 2.2.15?

**Comment by Natim** [comment]
Update your TINYMCE_DEFAULT_CONFIG to one of the examples here : https://www.tiny.cloud/docs/demo/full-featured/
