### ISSUE TITLE
Spaces removed because of bad django HTML escaping

### ISSUE THREAD

**Issue by sdeleon28** [aljosa/django-tinymce#38]
I have this markup in my database:
    `<p>hello </p>` // Notice there's a space after hello

The widget gets rendered as:
    `<textarea><p>hello </p></textarea>`

Which results in the browser deleting spaces at the end.

This happens because on line 82 of tinymce/widgets.py the code uses Django's builtin escape function to escape html within the content of my database attribute. The solution is to replace that call with a call to the following function, that replaces all spaces for &nsbp; chars.

    def html_escape(text):
        return escape(text).replace(' ', '&nbsp;')

**Comment by Natim** [comment]
Stripping looks like a feature rather than a bug to me.
