### ISSUE TITLE
add cache key to /compressor url

### ISSUE THREAD

**Issue by evgenyfadeev** [aljosa/django-tinymce#42]
is it possible to change compressor url to /compressor/some-cache-code/?

I ran into a difficulty busting the cache when compressor is enabled with a custom plugin.

Found a bug in a plugin affecting IE, now can't deploy the fix because of very sticky cache.

Thank you.

**Comment by Natim** [comment]
That's something we should work on. Do you want to tackle this?

**Comment by Natim** [comment]
I think the easy way to do it, is to take a hash of the content here: https://github.com/aljosa/django-tinymce/blob/master/tinymce/compressor.py#L138-L139

And add a ETag header with it.

**Comment by Natim** [comment]
It seems to be the case but we may add a test for it.
