### ISSUE TITLE
Problem with CachedStaticFilesStorage when run collectstatic

### ISSUE THREAD

**Issue by applecat** [aljosa/django-tinymce#45]
I have a problem with the collectstatic command when enabling this setting: 
'STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage':
ValueError: The file 'tiny_mce/plugins/fullpage/images/add.gif' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x103b7090>.

How I cat fix this?

**Comment by Natim** [comment]
Documented on: https://github.com/aljosa/django-tinymce/commit/214e1c6afb8d3c26417afc00bdbae3e3d8a71aae
