### ISSUE TITLE
TinyMCE tries to import plugins/paste/plugin.min.js

### ISSUE THREAD

**Issue by DeD1rk** [aljosa/django-tinymce#476]
Tinymce is trying to import the `paste` plugin that, since updating from 3.7.1 to 4.1.0, does not exist in this package.

<img width="571" alt="image" src="https://github.com/user-attachments/assets/ed6ca532-3fe8-4898-bf07-d803ec83c2ac">

When doing the same on my production application, it is therefore loading the old versionof that plugin (Version: 5.10.7), which causes copying and pasting to be buggy/impossible there. 

On my local version (where it gets 404, not an old version), the copying and pasting is fine, but still, it shouldn't try to get a file that will 404.

**Comment by DeD1rk** [comment]
Something related is that the tinymce files don't seem to use django's ManifestFilesMixin, which:
- causes the production version to load the old plugin instead of 404
- causes issues where clients were still on the old version because all of the files were cached

**Comment by claudep** [comment]
Usage of ManifestFilesMixin is never forced by 3rd-party apps, you should set it up in your projects.

Indeed paste is no longer a plugin in TinyMCE 6, see https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-core-changes/#removed-or-deprecated-plugins-paste. You should remove it from your plugin list.

**Comment by DeD1rk** [comment]
@claudep I see, removing the plugin works to get rid of the 404. I hadn't seen that in the changelogs.

Regarding the ManifestFilesMixin, I have set it up in production. But only a few of the django-tinymce files are actually referenced by the hashed urls (see also #266). Any files referenced _from_ tinymce.min.js use the plain url. Using the `cache_suffix` config works, but something more automatic would be really nice.
