### ISSUE TITLE
Problem with relative URLs

### ISSUE THREAD

**Issue by GMLudo** [aljosa/django-tinymce#49]
Hi,

When I use tinymce, I want to have the urls of images like: /static/images/example.png when I save the form.
I've tried all solutions on:
http://www.tinymce.com/wiki.php/TinyMCE_FAQ#Paths.2FURLs_are_incorrect.2C_I_want_absolute.2Frelative_URLs.3F
and:
http://www.tinymce.com/tryit/url_conversion.php

I have only two possible results:
1. ../../../../../../../static/images/example.png
2. static/images/example.png (without the / at the beginning)

Even with 'convert_urls' : 'false', I've a conversion when I set /static/images/example.png.

I use the latest version of django-tinymce, with chromium.

Do you have an idea to fix the problem ?

Thanks for your answer.

**Comment by elky** [comment]
I spent about an hour to realize that ```'relative_urls' : 'false'``` doesn't work. You need to use ```'relative_urls' : False``` to make it work. Thanks @caa
