### ISSUE TITLE
Attribute cols doesn't work when 'classes': ['collapse'] is setted on fieldset

### ISSUE THREAD

**Issue by 8ksoft** [aljosa/django-tinymce#53]
Hi,

When I use the widget in the django admin, i cannot set 'cols', if use fieldsets and 'classes': ['collapse'].

Supose I have a tinymce charfield, and the put this into an admin fieldset

```python
class FlatPageForm(forms.ModelForm):
    ...
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 120, 'rows': 30}))
    ...


class FlatAdmin(ModelAdmin):
    fieldsets = [
        ...
        ('Foo', {'fields': ['content',],'classes': ['collapse']}),
        ...
    ]

```

Then, the result is not seen properly the widget with 120 cols!

Thanks!, 
Mario.

**Comment by vanadium23** [comment]
I'll close issue due to old and not reproducing. Thanks for reporting.
