### ISSUE TITLE
Compressor not working with Django 1.5

### ISSUE THREAD

**Issue by framazz** [aljosa/django-tinymce#59]
I installed django-tinymce with pip, as suggested, so I have version 1.5.1b4
I'm using Django 1.5.

My settings.py contains:
INSTALLED_APPS = (
[omissis]
'django.contrib.staticfiles',
'tinymce',
)
TINYMCE_JS_URL = os.path.join(STATIC_URL, "tiny_mce/tiny_mce_src.js")
TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT, "tiny_mce")
TINYMCE_DEFAULT_CONFIG = {
'cleanup_on_startup': True,
'custom_undo_redo_levels':20,
}
#TINYMCE_COMPRESSOR = True

My urls.py includes
url(r'^tinymce/', include('tinymce.urls')),

If i leave the
TINYMCE_COMPRESSOR = True commented out, it works and I see the WYSIWYG tool, if I uncomment it, there is a simple textbox.

I modified templates/tinymce/tiny_mce_gzip.js adding {% load url from future %} and
modified {% url tinimce-compressor %}
to {% url "tinimce-compressor" %}

otherwise Django was complaining that it
"Could not parse the remainder: '-compressor' from 'tinymce-compressor'."

**Comment by Natim** [comment]
Related to #50
