### ISSUE TITLE
Integrating TinyMCE 4

### ISSUE THREAD

**Issue by mvattuone** [aljosa/django-tinymce#61]
Hi,

Has anyone attempted to integrate the latest TinyMCE build into django-tinymce?  I've currently been giving it a go, but the settings for relative_urls seem to be ignored, and my URLs are not building correctly.

If anyone else is working on this, maybe we can work together to get this up and running?  Or are there plans to upgrade at a later time?

Thanks!

**Comment by Natim** [comment]
If people are interested on porting django-tinymce to TinyMCE 4, feel free to help.

**Comment by dani0805** [comment]
Hi,

We have been using tinymce4 with django-tinymce for almost a year now. It's stable and has no major issue. What can we do to speed up the release. We would love to stop pulling it from git every time.

**Comment by Natim** [comment]
We have many proposition for that:

 - Either we create a new django-tinymce4 project
 - Either we create a new django-tinymce 3.x branch and we start deprecating the 2.x branch

**Comment by Natim** [comment]
Note that we will need to make sure tests and documentation are up-to-date.

**Comment by dani0805** [comment]
I would tend for option 1 as there might still be people using the legacy version. The Documentation is kind of cut/paste from the old one except for a few details (e.g. profile) and a big link to tinymce4 documentation. We could do that. When you say tests you mean automated tests?

**Comment by aljosa** [comment]
pypi has an option to hide releases so you could in theory deploy new release (django-tinymce==3.x) to pypi and hide it.
people using 2.x wouldn't notice anything and anybody aware of 3.x could install it by targeting a specific pypi release.

**Comment by dani0805** [comment]
actually if they froze correctly their settings there should be no problem even if 3.x is not hidden

**Comment by jherrlin** [comment]
I have interest in getting TinyMCE 4 support, and willing to spend time help with development / testing.

**Comment by dani0805** [comment]
I am working right now on integrating the latest version and update the documentation. Will post my work soon.

But, I never contributed to an official project ;-) what I am supposed to do? Pull request?

**Comment by dani0805** [comment]
So I have locally upgraded tinymce to 4.2.4, extended the documentation (the part that took some figuring out few months ago) and bumped the version. I have installed it locally and tested it within our application and seems fine.

**Comment by dani0805** [comment]
Pull request is there.

**Comment by Natim** [comment]
Fixed with #128 — I have released an hidden django-tinymce===3.0.0 for you to try.

**Comment by Natim** [comment]
Actually I didn't noticed that the PR was on tinymce4 rather than master.

**Comment by Natim** [comment]
We will need to prepare a clean merge for tinymce4 and master before going forward.

**Comment by dani0805** [comment]
Ok I'll merge and prepare a pull request on master

**Comment by dani0805** [comment]
I just sent a pull request for master I tried my best at merging them but they were quite different.. I tested it briefly in my application to see if everything was still working compared to tinymce4 branch and it seems ok

**Comment by dani0805** [comment]
Any news on this? We can also fork the tinymce4 into a new project and take it from there...

**Comment by Natim** [comment]
> We can also fork the tinymce4 into a new project and take it from there...

It sound a reasonable choice to me.

**Comment by dani0805** [comment]
Should I do it or you want to do it?

**Comment by Natim** [comment]
If you feel like maintening it you are most welcome :+1:

**Comment by dani0805** [comment]
I have no idea if I will be able to, lets see... For now I will fork it adjust the comments and links to the right repo and post it to pipy as django-tinymce4

**Comment by Natim** [comment]
Feel free to add @aljosa and I to the contrib of your repository.

**Comment by dani0805** [comment]
of course

**Comment by dani0805** [comment]
done and submitted to pipy, already available online as django-tinymce4.

Enjoy

**Comment by Natim** [comment]
Youhou, great.

**Comment by glassfordm** [comment]
For me, django-tinymce4 on pypi / the tinymce4 branch didn't work. It seems unmaintained, eliminates features I need (such as TINYMCE_JS_URL), and I believe sure has some issues with newer versions of Django.

See this Pull Request for an alternative: https://github.com/aljosa/django-tinymce/pull/239
