### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by dmoisset** [aljosa/django-tinymce#70]
The manual ha links to http://wiki.moxiecode.com/index.php/TinyMCE:Configuration and to http://wiki.moxiecode.com/index.php/TinyMCE:Custom_filebrowser ; both are down now

I think the links should point to http://www.tinymce.com/wiki.php/configuration and http://www.tinymce.com/wiki.php/TinyMCE3x:How-to_implement_a_custom_file_browser

**Comment by Natim** [comment]
Can you make a PR to fix this? Thanks.

**Comment by Natim** [comment]
Fixed with aa09eb3
