### ISSUE TITLE
'ascii' codec can't codec HTMLField()

### ISSUE THREAD

**Issue by pythdasch** [aljosa/django-tinymce#73]
After more or less 2 days to try to debug this problem. the problem is that in the admin, the HTMLField isn't displayed. it's blank.

So I came to debug on the shell and I found this error :
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

home/david/src/atmosphere/venv/local/lib/python2.7/site-packages/tinymce/widgets.pyc in get_language_config(content_language)
    153     for lang, name in settings.LANGUAGES:
    154         if lang[:2] not in lang_names: lang_names[lang[:2]] = []
--> 155         lang_names[lang[:2]].append(_(name))
    156     sp_langs = []
    157     for lang, names in lang_names.items():

and after it's django stacktrace.

Have you already faces this problem ? Have you some advice to correct it ?

Thanks you in advance

**Comment by Natim** [comment]
Closing since this issue is more than 2 years old. Feel free to reopen.
