### ISSUE TITLE
image javascript:openBrowser  open 127.0.0.1 page

### ISSUE THREAD

**Issue by jiangzhx** [aljosa/django-tinymce#75]
![1](https://f.cloud.github.com/assets/494507/1100849/88d395a4-1790-11e3-9eec-765268d0265f.jpg)

![2](https://f.cloud.github.com/assets/494507/1100845/719d55be-1790-11e3-8d05-d59593e33907.jpg)

when i click   javascript:openBrowser('srcbrowser','src', 'image','theme_advanced_image_image_browser_callback');

then open a 127.0.0. server page. 

![3](https://f.cloud.github.com/assets/494507/1100846/719cbd34-1790-11e3-97db-f4f5ecdf23b8.jpg)

the domain is diff.

**Comment by Natim** [comment]
Looks like a configuration issue on the settings.py
