### ISSUE TITLE
Tinymce field disabled sometimes

### ISSUE THREAD

**Issue by apalazon** [aljosa/django-tinymce#76]
Dear all,

I'm using tatest pypi version of django-tinymce with django 1.4.8 and apache2 as a production enviroment and sometimes I have a problem.

Sometimes, on production, all of the application TinyMCE fields are shown as read only fields. I use multiple browsers, and I see the problem on all.

When I restart the Apache server, the problem dissapears itself. After some time, it appears again.

I cannot replicate the problem on my development enviroment.

I have checked that the javascript output is the same as expected. 

Using Firebug, the only difference that I have seen on the page render is the following:

Bad, read only version:
```
<body id="tinymce" class="mceContentBody " onload="window.parent.tinyMCE.get('id_foro-descripcionhtml').onLoad.dispatch();" spellcheck="false" dir="ltr">
```
Good version:
```
<body id="tinymce" class="mceContentBody " contenteditable="true" onload="window.parent.tinyMCE.get('id_foro-descripcionhtml').onLoad.dispatch();" spellcheck="false" dir="ltr">
```

The difference is that the good version has the contenteditable="true" atribute.

What could be the problem? May it be a "race condition" on TinyMCE javascript load? Or some Apache multithreading problem?

Thank you, best regards,

**Comment by Natim** [comment]
Closing since this issue is more than 2 years old. Feel free to reopen.
