### ISSUE TITLE
TinyMCE widget renders tinyMCE.init repeatedly!

### ISSUE THREAD

**Issue by xgfone** [aljosa/django-tinymce#78]
In a model, I define one HTMLField and more TextFields,  and it all going well.

But when defined more HTMLFields in one model, trouble arised. That's, on the same  "mode" in tinymce 3.X, such as "textareas", TinyMCE.init is rendered repeatedly! It should not be! it is the result that I can't resize the size of HTMLField through draging.

**Comment by Natim** [comment]
Closing since this issue is almost 2 years old, feel free to reopen with new insights.
