### ISSUE TITLE
Enabling I18N causes all TinyMCE widgets to disappear

### ISSUE THREAD

**Issue by chrisspen** [aljosa/django-tinymce#82]
If I set `USE_I18N = True` in my settings.py, all TinyMCE widgets vanish. Looking at my page source, the TinyMCE widget isn't rendering any markup.

**Comment by Natim** [comment]
This has been documented with https://github.com/aljosa/django-tinymce/commit/214e1c6afb8d3c26417afc00bdbae3e3d8a71aae
