### ISSUE TITLE
tinymce 1.5.2 with bootstrap3

### ISSUE THREAD

**Issue by bearmingo** [aljosa/django-tinymce#85]
I use django-tinymce and bootstrap3 in my page. It can't popup window when I click  style button in TinyMCE. And the word style is not correct

**Comment by Natim** [comment]
I am closing since we didn't get feedback for more than a year. Feel free to reopen.

**Comment by admed** [comment]
Hi, 
I have the same issue,
When using django_boostrap3 with django_tinymce I can't submit a form in google chrome,
The same issue is in firefox but when I reload the page the form can be submited.
I'm using also jquery version 2.2.4.

When I comment the {{ form.media }} in my template (no tinymce for textarea) the form can be submitted.
