### ISSUE TITLE
Python 3 classifiers

### ISSUE THREAD

**Issue by hwkns** [aljosa/django-tinymce#94]
Does django-tinymce officially support Python 3?

If so, it would be nice to designate that on PyPI using classifiers in setup.py (see https://pypi.python.org/pypi?%3Aaction=list_classifiers)

If not, what does the path forward look like?

**Comment by Natim** [comment]
I know people used it with Python3 feel free to open issue if you have some.
Feel free to make a PR to add this classifier?
